# Practical 8: Grid Search

## Grid Search with KNN

In [1]:
from pprint import pprint

import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import matplotlib.pyplot as plt

In [2]:
X, y = load_iris(return_X_y=True)

X_train, y_train = X[0:150:2, ...], y[0:150:2]
X_test, y_test = X[1:150:2, ...], y[1:150:2]

In [3]:
param_grid = {
    'n_neighbors': [1, 5, 10, 20],
    'weights'    : ['distance', 'uniform']
}

In [4]:
knn_model = KNeighborsClassifier()

In [5]:
search_model = GridSearchCV(knn_model, param_grid, n_jobs=-1, scoring='accuracy')

In [6]:
search_model.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 5, 10, 20],
                         'weights': ['distance', 'uniform']},
             scoring='accuracy')

In [7]:
print(search_model.best_params_)

{'n_neighbors': 5, 'weights': 'distance'}


In [8]:
y_pred = search_model.predict(X_test)

In [9]:
print(f"accuracy : {accuracy_score(y_test, y_pred)}")

accuracy : 0.9866666666666667


In [10]:
print(confusion_matrix(y_test, y_pred))

[[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75



In [12]:
pprint(search_model.cv_results_)

{'mean_fit_time': array([0.00123749, 0.00104709, 0.00074739, 0.00093012, 0.00112505,
       0.00167999, 0.00113368, 0.00099649]),
 'mean_score_time': array([0.00216441, 0.0022963 , 0.00125699, 0.00230079, 0.0017117 ,
       0.00364871, 0.00178022, 0.00270152]),
 'mean_test_score': array([0.94666667, 0.94666667, 0.96      , 0.96      , 0.96      ,
       0.94666667, 0.93333333, 0.92      ]),
 'param_n_neighbors': masked_array(data=[1, 1, 5, 5, 10, 10, 20, 20],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object),
 'param_weights': masked_array(data=['distance', 'uniform', 'distance', 'uniform',
                   'distance', 'uniform', 'distance', 'uniform'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object),
 'params': [{'n_neighbors': 1, 'weights': 'distance'},
            {'n_neighbors': 1, 'weights': 'uniform'},
            {'n_neighbors'

In [13]:
search_model.best_index_

2

## Grid Search with SVM

In [14]:
param_grid = {
    'penalty': ['l1', 'l2'],
    'loss'   : ['hinge', 'squared_hinge'],
    'C'      : [0.5, 1.0, 2.0, 5.0, 10.0]
}

In [15]:
svc_model = LinearSVC()

In [16]:
search_model = GridSearchCV(svc_model, param_grid, n_jobs=-1, scoring='accuracy')

In [17]:
search_model.fit(X_train, y_train)

/home/tirthasheshpatel/.local/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


GridSearchCV(estimator=LinearSVC(), n_jobs=-1,
             param_grid={'C': [0.5, 1.0, 2.0, 5.0, 10.0],
                         'loss': ['hinge', 'squared_hinge'],
                         'penalty': ['l1', 'l2']},
             scoring='accuracy')

In [18]:
print(search_model.best_params_)

{'C': 2.0, 'loss': 'squared_hinge', 'penalty': 'l2'}


In [19]:
y_pred = search_model.predict(X_test)

In [20]:
print(f"accuracy : {accuracy_score(y_test, y_pred)}")

accuracy : 0.96


In [21]:
print(confusion_matrix(y_test, y_pred))

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75



In [23]:
pprint(search_model.cv_results_)

{'mean_fit_time': array([0.00061183, 0.0020421 , 0.00053139, 0.00381536, 0.00060363,
       0.0018898 , 0.00064588, 0.00352216, 0.00076375, 0.0026484 ,
       0.0008472 , 0.00449581, 0.00100756, 0.0028203 , 0.00064654,
       0.00358768, 0.0006732 , 0.00335116, 0.00077519, 0.00315976]),
 'mean_score_time': array([0.        , 0.0004571 , 0.        , 0.00061364, 0.        ,
       0.00046411, 0.        , 0.00048261, 0.        , 0.00084252,
       0.        , 0.00056391, 0.        , 0.00049095, 0.        ,
       0.00058255, 0.        , 0.00068827, 0.        , 0.00035172]),
 'mean_test_score': array([       nan, 0.86666667,        nan, 0.96      ,        nan,
       0.93333333,        nan, 0.96      ,        nan, 0.93333333,
              nan, 0.97333333,        nan, 0.94666667,        nan,
       0.96      ,        nan, 0.94666667,        nan, 0.94666667]),
 'param_C': masked_array(data=[0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0,
                   2.0, 5.0, 5.0, 5.0, 5.0, 10

In [24]:
search_model.best_index_

11