# Practical 8: Grid Search

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import matplotlib.pyplot as plt

In [2]:
X, y = load_iris(return_X_y=True)

X_train, y_train = X[0:150:2, ...], y[0:150:2]
X_test, y_test = X[1:150:2, ...], y[1:150:2]

In [3]:
param_grid = {
    'n_neighbors': [1, 5, 10, 20],
    'weights'    : ['distance', 'uniform']
}

In [4]:
knn_model = KNeighborsClassifier()

In [5]:
search_model = GridSearchCV(knn_model, param_grid, n_jobs=-1, scoring='accuracy')

In [6]:
search_model.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 5, 10, 20],
                         'weights': ['distance', 'uniform']},
             scoring='accuracy')

In [7]:
print(search_model.best_params_)

{'n_neighbors': 5, 'weights': 'distance'}


In [8]:
y_pred = search_model.predict(X_test)

In [9]:
print(f"accuracy : {accuracy_score(y_test, y_pred)}")

accuracy : 0.9866666666666667


In [10]:
print(confusion_matrix(y_test, y_pred))

[[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75



In [47]:
from pprint import pprint
pprint(search_model.cv_results_)

{'mean_fit_time': array([0.00117993, 0.00080414, 0.00070376, 0.0012373 , 0.00111313,
       0.00101461, 0.00096841, 0.00098515]),
 'mean_score_time': array([0.00215125, 0.00181503, 0.00115652, 0.00266705, 0.00255475,
       0.00233536, 0.0018867 , 0.00233688]),
 'mean_test_score': array([0.94666667, 0.94666667, 0.96      , 0.96      , 0.96      ,
       0.94666667, 0.93333333, 0.92      ]),
 'param_n_neighbors': masked_array(data=[1, 1, 5, 5, 10, 10, 20, 20],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object),
 'param_weights': masked_array(data=['distance', 'uniform', 'distance', 'uniform',
                   'distance', 'uniform', 'distance', 'uniform'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object),
 'params': [{'n_neighbors': 1, 'weights': 'distance'},
            {'n_neighbors': 1, 'weights': 'uniform'},
            {'n_neighbors'

In [51]:
search_model.best_index_

2